### ISSUE TITLE
Design user flow for self serve monetization

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1001]
**Subflows**:

- [x] Account Creation
- [x] User Onboarding
- [x] Connection IDE <> Web Experience
- [x] Upgrading to Pro
- [ ] Upgrade to Enterprise

**Figma: https://www.figma.com/file/FMSdn1oKccJRHQPgf7053o/Cody-GA?type=design&node-id=2440%3A3594&mode=design&t=nOKAi7H8rmI8riZh-1**

(includes all the flows)

```[tasklist]
### Tasks
- [x] [DESIGN] [DEC Release] Account Creation Flow
- [x] [DESIGN] [DEC Release] User Onboarding
- [x] [DESIGN] [DEC Release] Connection IDE <> Web Experience
- [x] [DESIGN] [DEC Release] Upgrading to Pro
- [x] [DESIGN] [FEB Release] Checkout Flow
- [ ] [DESIGN] [After FEB Release] Upgrade to Enterprise
- [ ] [DESIGN] [After FEB Release] Team Management
```

**Comment by thenamankumar** [comment]
@danielmarquespt the Figma file link here needs to be updated to match the Dec GA scope.

**Comment by danielmarquespt** [comment]
Updated the task with the link to the figma file. Since all of these flows derive from a central experience, everithing is set inside that figma file

More details:
https://sourcegraph.slack.com/archives/C066F85TE80/p1700069443011979

**Comment by danielmarquespt** [comment]
Update on this:

Designs peding are the Upgrade to enterprise and the Team Management flow, as these are not part of the February release. Also the "Upgrade to Enterprise" is not clearly defined right now.

Im closing this issue for now as most of the design work is done.

Will create new design tasks after we figure out the scope of the next release
