### ISSUE TITLE
Tracking issue: 9/21 - 10/4

### ISSUE THREAD

**Issue by beyang** [sourcegraph/cody#1151]
```[tasklist]
- [ ] https://github.com/sourcegraph/cody/issues/924
- [ ] https://github.com/sourcegraph/cody/issues/808
- [ ] https://github.com/sourcegraph/cody/issues/940
- [ ] https://github.com/sourcegraph/cody/issues/632
- [ ] https://github.com/sourcegraph/cody/issues/1175
- [ ] https://github.com/sourcegraph/cody/issues/1176
- [ ] https://github.com/sourcegraph/cody/issues/1177
- [x] [Olaf + Auguste] Categorize completions by type using additional syntactic clues + change behavior (single vs multiline, latency)
- [ ] https://github.com/sourcegraph/cody/issues/1157
- [ ] https://github.com/sourcegraph/cody/issues/1054
- [x] [Beyang + Kevin] CAR and Weighted CAR definition and reporting
- [x] [Tom] Cody vs competition example GIFs
- [x] [Philipp] Track explicit triggers in completions metadata (if not already done)
- [ ] [Beyang] Use logprobs from StarCoder as signal for confidence, cycle through suggestions in order
- [ ] https://github.com/sourcegraph/cody/issues/667
- [ ] https://github.com/sourcegraph/cody/issues/1096
- [ ] https://github.com/sourcegraph/cody/issues/910
- [ ] https://github.com/sourcegraph/cody/issues/860
- [ ] https://github.com/sourcegraph/cody/issues/1070
- [ ] https://github.com/sourcegraph/cody/issues/1178
- [ ] https://github.com/sourcegraph/cody/issues/1195
- [ ] https://github.com/sourcegraph/cody/issues/1275
- [ ] https://github.com/sourcegraph/cody/issues/1276
```

```[tasklist]
### Revisit post-Oct 4
- [ ] https://github.com/sourcegraph/app/issues/68
- [ ] https://github.com/sourcegraph/cody/issues/789
- [ ] https://github.com/sourcegraph/cody/issues/1049
- [ ] https://github.com/sourcegraph/cody/issues/1050
- [ ] https://github.com/sourcegraph/cody/issues/1138
- [ ] https://github.com/sourcegraph/cody/issues/1097
- [ ] https://github.com/sourcegraph/cody/issues/1010
- [ ] Multiregion deployment
- [ ] Use tree-sitter to check whether there are a lot of made-up symbol
- [ ] Code Llama
- [ ] [Pin LLM versions](https://sourcegraph.slack.com/archives/C05AGQYD528/p1695849038538219?thread_ts=1695848852.257419&cid=C05AGQYD528)
- [ ] https://github.com/sourcegraph/cody/pull/1152
- [ ] Self-hosted completions
- [ ] https://github.com/sourcegraph/cody/issues/1229
- [ ] Block Cody abuse by checking against prompt templates ([context](https://sourcegraph.slack.com/archives/C0C324C91/p1696322332990229))
- [ ] Make use of GPT-4 for code generation?
- [ ] https://github.com/sourcegraph/cody/issues/667
- [ ] https://github.com/sourcegraph/cody/issues/951
- [ ] [Anthropic prompt validation](https://sourcegraph.slack.com/archives/C04D0GRD1GB/p1696608580100329)
- [ ] Telemetry for chat/commands, including what sort of context is used
- [ ] https://github.com/sourcegraph/cody/issues/1350
```
```[tasklist]
### Revisit Nov 1
- [ ] [Automated release process with integration test for all clients](https://sourcegraph.slack.com/archives/C04MZPE4JKD/p1696866464146509?thread_ts=1696444672.205249&cid=C04MZPE4JKD)
```
