### ISSUE TITLE
Tracking issue: 10/4 - 11/1

### ISSUE THREAD

**Issue by beyang** [sourcegraph/cody#1354]
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/cody/issues/667
- [ ] https://github.com/sourcegraph/cody/issues/1406
- [ ] https://github.com/sourcegraph/cody/issues/1407
- [x] [Danny + Tim] Onboarding + Windows
- [ ] https://github.com/sourcegraph/cody/issues/1229
- [ ] https://github.com/sourcegraph/cody/issues/632
- [x] [Olaf + Auguste] Graph context
- [ ] https://github.com/sourcegraph/cody/issues/1157
- [x] [Tom] Fixup and Fixup action
- [x] [Beatrix, Philipp] Ongoing feature flags / experiments: (1) user-based completion latency, (2) LSP graph context
- [ ] https://github.com/sourcegraph/cody/issues/1451
- [ ] https://github.com/sourcegraph/cody/pull/1351
- [x] [Beyang] Support transition (work with devrel)
- [x] [Olaf] Integration test suite for agent (JetBrains incident follow-up)
- [ ] https://github.com/sourcegraph/cody/issues/1362
- [ ] https://github.com/sourcegraph/cody/issues/1438
- [ ] https://github.com/sourcegraph/cody/issues/951
```

```[tasklist]
### Punted
- [ ] https://github.com/sourcegraph/cody/issues/1370
- [ ] [Unassigned] Block Cody abuse by checking against prompt templates ([context](https://sourcegraph.slack.com/archives/C0C324C91/p1696322332990229))
- [ ] [Unassigned] [Anthropic prompt validation](https://sourcegraph.slack.com/archives/C04D0GRD1GB/p1696608580100329)
```

```[tasklist]
### Spilled over
- [ ] [Valery] full function completions
- [ ] [Auguste] BFG
- [ ] https://github.com/sourcegraph/cody/issues/1366
- [ ] https://github.com/sourcegraph/cody/issues/1097
- [ ] https://github.com/sourcegraph/cody/issues/1410
- [ ] https://github.com/sourcegraph/cody/issues/1377
- [ ] https://github.com/sourcegraph/cody/issues/1455
- [ ] https://github.com/sourcegraph/cody/issues/1464
- [ ] https://github.com/sourcegraph/cody/issues/1359
- [ ] https://github.com/sourcegraph/cody/issues/1369
- [ ] [Beatrix + Beyang + Tim to discuss] Generate tests
- [ ] https://github.com/sourcegraph/cody/issues/1378
- [ ] [Kevin + Beyang] Loveability metrics for commands/chat
- [ ] https://github.com/sourcegraph/cody/issues/1049
- [ ] https://github.com/sourcegraph/cody/issues/1545
```

```[tasklist]
### Revisit Nov 1
- [ ] https://github.com/sourcegraph/app/issues/68
- [ ] https://github.com/sourcegraph/cody/issues/789
- [ ] https://github.com/sourcegraph/cody/issues/1050
- [ ] https://github.com/sourcegraph/cody/issues/1138
- [ ] https://github.com/sourcegraph/cody/issues/1010
- [ ] Multiregion deployment
- [ ] Use tree-sitter to check whether there are a lot of made-up symbol
- [ ] Code Llama
- [ ] [Pin LLM versions](https://sourcegraph.slack.com/archives/C05AGQYD528/p1695849038538219?thread_ts=1695848852.257419&cid=C05AGQYD528)
- [ ] https://github.com/sourcegraph/cody/pull/1152
- [ ] Make use of GPT-4 for code generation?
- [ ] https://github.com/sourcegraph/cody/issues/667
- [ ] https://github.com/sourcegraph/cody/issues/1350
- [ ] [Automated release process with integration test for all clients](https://sourcegraph.slack.com/archives/C04MZPE4JKD/p1696866464146509?thread_ts=1696444672.205249&cid=C04MZPE4JKD)
- [ ] [GA] Pro tier rate limit enforcement
- [ ] https://github.com/sourcegraph/cody/issues/1475
```
