### ISSUE TITLE
Design tracking issue: Commands up-front and No Magic Chat

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#1377]
A new Cody design that brings it more in line with ChatGPT, and makes Cody's sidebar less chat-centric, the goal of:

- Transparency & Control (less magic)
  - Show underlying chat w/ LLM, model, tokens, etc
  - Less "Cody speaking" more "raw LLM w/ some context"
  - Explicit control of context, file selection, embeddings, etc
- Readability
  - Chat layout w/ more room
- Learnability
  - Put commands front-and-center
  - More visible controls for first time users
  - In-product help/references (e.g. keyboard shortcut reference)
  - More accessible Cody statusbar button
- Addition of natural language search
- Allow for self-serve monetisation (an "account" view/pane, understanding limits/quota, visualising LOC/usage)

Design research: https://docs.google.com/document/d/1YniwIBjLb91KKN-tC_9ewCtgx-JeCko62uK8tdFlFpY/edit#heading=h.sqmt908y46fi

Figma: https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1-52&mode=design

Interactions to design:
- [x] Overall Cody layout
- [ ] Commands
  - [x] List in sidebar
    - [x] Feedback: custom prompts too hidden
  - [ ] Pending edits visibility (i.e. replace old fixups sidebar)
- [ ] Chat
  - [x] List in sidebar
  - [x] @-file in message
  - [x] Context providers (WIP)
  - [x] Viewing context
  - [ ] Raw view
  - [ ] Later: Chat list in quickpick
  - [ ] Later: intent detection/hints
  - [ ] Later: dedicated sidebar mode
- [x] Search
  - [ ] Results
  - [ ] Later: start chat from result
- [ ] Onboarding
  - [x] Chat
  - [ ] Commands
  - [ ] Autocomplete
- [ ] Update notifications
- [x] Settings & docs
  - [x] Feedback: missing autocomplete settings
- [x] Updated statusbar button

**Comment by toolmantim** [comment]
First version of a design concept.

The after-login experience:

![image](https://github.com/sourcegraph/cody/assets/153/5011e46e-ccf0-4cd5-9b84-eb0d128fafa2)

The chat experience:

![image](https://github.com/sourcegraph/cody/assets/153/d2e9ccab-c3f0-4b85-8ec1-a0673c9658d2)

Notes:
- Uses [viewsWelcome](https://code.visualstudio.com/api/references/contribution-points#contributes.viewsWelcome) to do the welcome views for search and chat
- There is no sidebar chat experience. Can an extension provide two completely different roo level views with sidebar icons? Because if so, we could introduce a dedicated chat sidebar item later?

**Comment by beyang** [comment]
> Sadly we can't do a proper search input in a treeview, so instead we use the viewsWelcome to put a button, and a quickpick for the input. Better than using a webview, because we want the treeview for the search results.

Once the search results are displayed, does that mean there will still be a button at the top that users must click to type a new query?

> There is no sidebar chat experience. Can an extension provide two completely different roo level views with sidebar icons? Because if so, we could introduce a dedicated chat sidebar item later?

I like the "chat in buffer" view and might prefer it to chat in the sidebar.

**Comment by abeatrix** [comment]
@toolmantim Are we going to move the auth view into a sidebar panel if we are removing the webview from the sidebar?

**Comment by toolmantim** [comment]
@abeatrix I expected the auth view will largly be the same… a single webview with no other views active. Is that possible?

**Comment by toolmantim** [comment]
New designs that fleshes out about 80% of the magic-less Cody chat + commands up-front experience. The intention is for this to be on the side of "no magic", and giving users confidence and control, as we have clear terminology for things, and nothing is automatically injected into chat that you haven't enabled.

Figma:
https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=71-41447&mode=design&t=g4Li03r8yRJVw1Jh-4

Loom:
https://www.loom.com/share/69c1c670578347d7883fd5da6f22d500

It introduces:
- Chat "Context Providers"
- A more prominent "Raw View" button
- Embeddings experience (and how it'd work with multi-repo)
- New LLM chooser w/ provider icons

Questions:
- Are we aligned on the overall mental models laid out here, esp. "Context Providers"
- Do these designs align w/ what will be the underlying eng architecture?
- Do we have a singleton chat view, or can you open multiple chats at once?
- What do we name search? I used "Cody Search" but it's very similar to "Code Search". Should it be "Symbol Search"? Depends on the vision for what it is @beyang. Let's discuss this elsewhere.

Things still to do:
- Overall onboarding experience / guides
- Autocomplete guidance/onboarding

**Comment by abeatrix** [comment]
As discussed yesterday, I've removed the fixup view from my PR so you can play around with it and see how you feel.

> There is no sidebar chat experience. Can an extension provide two completely different roo level views with sidebar icons? Because if so, we could introduce a dedicated chat sidebar item later?

Yes. 

> Do we have a singleton chat view, or can you open multiple chats at once?

I'd suggest start with one because of how resource intensive a web view can be.

**Comment by toolmantim** [comment]
I've added an overall todo list to the issue description to track progress and feedback

**Comment by toolmantim** [comment]
A new version of this taking on various bits of feedback, and simplifying things:

![image](https://github.com/sourcegraph/cody/assets/153/acca96c0-0952-4b25-b3be-e5d086053af8)

Loom walkthrough:
https://www.loom.com/share/4ce0ae567a1449e890fab3b42fd1bb4e

Changes:

- Simplified getting started tour (only a single glowing dot on first chat)
- Simplified the context management down a single checkbox ("Enhanced Context"), made embeddings setup a one click process (per-repo), and a single "Learn more" link to docs to explain what the options in this dialog are.
- New "Custom Commands" item in commands
- Updated chat icons
- Updated Setting & Support items

The context management states:
![image](https://github.com/sourcegraph/cody/assets/153/ec4cc536-8dc9-4ec9-89e6-ef7354bcb11b)

Figma: https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=209-43481&mode=design&t=FG0QLCvaP1Yov71o-4

**Comment by toolmantim** [comment]
Added [v4.1 frames to the Figma](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=331-114717&mode=design&t=h3K1lWaJE5Gb6Uv1-4), with updated copy for the Enhanced Context popover:

![image](https://github.com/sourcegraph/cody/assets/153/fa39d9da-434b-4b46-95ee-f67fe3a02050)

and flows for how the @-file interaction could work:

![image](https://github.com/sourcegraph/cody/assets/153/9ce0bac4-25ac-4b66-903e-9ab4669dac7e)

![image](https://github.com/sourcegraph/cody/assets/153/36a6778e-4ab5-445d-bb76-7674a2f0b05e)

![image](https://github.com/sourcegraph/cody/assets/153/fd33122e-7380-49dc-b79f-b7fbf5ecdd78)

![image](https://github.com/sourcegraph/cody/assets/153/13952a99-623c-47c5-a0ff-586562bad726)

![image](https://github.com/sourcegraph/cody/assets/153/30353b82-4b64-43a9-9f3c-54b8b2c9051a)

![image](https://github.com/sourcegraph/cody/assets/153/79e03031-8b43-4a3f-b932-2800b0d9ac86)

**Comment by fisforfaheem** [comment]
want to see this in latets version on vscodE!

**Comment by abeatrix** [comment]
@toolmantim Should we also move the `VersionUpdatedNotice` to the side panel?

**Comment by fisforfaheem** [comment]
Yes, you can do that.

**Comment by toolmantim** [comment]
@abeatrix yep, that's on the design todo list! Now we have a "Release Notes" treeview item I think we can adapt that perhaps? We'd still want to make sure it's not easily missed though. Ideally we show the notes in an editor tab 🤔

**Comment by beyang** [comment]
Can we close this or is there still outstanding stuff to do on this?
