### ISSUE TITLE
[Tracking Issue]: Refactor Chat to No-magic Chat

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#1410]
[Beatrix + Beyang + Tim] No-magic Chat

Design: https://github.com/sourcegraph/cody/issues/1377
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/cody/pull/1486
- [ ] https://github.com/sourcegraph/cody/issues/1521
- [ ] https://github.com/sourcegraph/cody/issues/1520
- [ ] https://github.com/sourcegraph/cody/pull/1442
- [ ] https://github.com/sourcegraph/cody/issues/1475
- [ ] https://github.com/sourcegraph/cody/issues/1522
- [ ] https://github.com/sourcegraph/cody/issues/1523
- [ ] https://github.com/sourcegraph/cody/issues/1524
- [ ] https://github.com/sourcegraph/cody/issues/1525
- [ ] https://github.com/sourcegraph/cody/issues/1526
- [ ] https://github.com/sourcegraph/cody/issues/1527
- [ ] Add Tests for new Chat UI
```

**Comment by abeatrix** [comment]
I think I have implemented lost of the expected features for the new chat design that are listed in this issus. I started the works on improving the test command and commands in generalC found some bugs I need to fix, as well as looking into the Cody ignore file, but I will keep working on polishing the UI following your figma more closely.

In the meantime, can you please let me know if there are features in your design that I haven't worked on yet?

- One thing I can think of is the token counting pop up when a file is too big, which I am not sure if we have a reliable way to do it.

- Another thing is the welcome view of the chat. In your design that area is empty. Can you confirm if that's the design and I should remove all the current welcome text? For both new and existing users? 

Anything else?

**Comment by abeatrix** [comment]
@toolmantim I think I have implemented lost of the expected features for the new chat design that are listed in this issus. I started the works on improving the test command and commands in general, found some bugs I need to fix, as well as looking into the Cody ignore file, but I will keep working on polishing the UI following Tim's figma more closely.

In the meantime, can you please let me know if there are any high priority features that I haven't worked on yet?

- One thing I can think of is the token counting pop up when a file is too big, which I am not sure if we have a reliable way to do it.

- Another thing is the welcome view of the chat (hello I'm Cody) In Tim's design that area is empty. Can you confirm if that's the design and I should remove all the current welcome text? For both new and existing users? 

Anything else?

**Comment by beyang** [comment]
Closing this, will pull in the remaining issue into the project board separately
