### ISSUE TITLE
Tracking issue: tree-sitter based completion intents (syntactic triggers)

### ISSUE THREAD

**Issue by valerybugakov** [sourcegraph/cody#1455]
A tracking issue for the tree-sitter-based completion intent work based on [RFC 848: Tree-sitter-powered intent detection for Cody](https://docs.google.com/document/d/13kYxtJcgoDAY45vulenwGtOW0KnugJPD31MXx-sgx2c/edit#heading=h.rabgao4dn1l):

```[tasklist]
### Completion Intents
- [x] https://github.com/sourcegraph/cody/issues/1451
- [ ] https://github.com/sourcegraph/cody/issues/1452
- [x] https://github.com/sourcegraph/cody/issues/1453
- [ ] https://github.com/sourcegraph/cody/issues/1454
- [ ] https://github.com/sourcegraph/cody/issues/1456
- [ ] https://github.com/sourcegraph/cody/issues/1470
- [x] https://github.com/sourcegraph/cody/issues/1472
```

```[tasklist]
### UPD
- [x] Use completion intent info to track CAR more granularly in Looker. Update the existing queries/logic if needed.
- [x] Pending the disable-streaming-truncation experiment results, consider leveraging intent information to expand the token limit for function/class declaration completion intents.
- [x] Analyze the results of the `syntactic-triggers` experiment where we switched multiline completions to singleline for type/struct/interface declaration intents. If this change positively affects CAR, make this a default behavior.
- [x] Make javascript completion intent queries more precise
```

### After GA Tasks:

```[tasklist]
### After GA
```

**Comment by valerybugakov** [comment]
Closing this tracking issue since the remaining issues are low priority, and we can review them separately. I added them to the eng tracking board.
