### ISSUE TITLE
VSCE: Improve Generate Unit Tests command

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#1475]
Design: https://github.com/sourcegraph/cody/issues/1359
https://github.com/sourcegraph/cody/issues/1359

Helpful feedback from users: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1698096296523479

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/cody/issues/1761
- [ ] https://github.com/sourcegraph/cody/pull/2646
- [ ] https://github.com/sourcegraph/cody/issues/2758
- [ ] https://github.com/sourcegraph/cody/pull/2959
```

TBD: 
- new edit mode for creating file with new content?
- make context for edit commands configurable

#### Claude 

Based on the shared context, the test framework in use is Vitest and the following libraries are imported:

```
import { describe, expect, it, test } from 'vitest'
import * as vscode from 'vscode'
```

No new imports are needed since Vitest and VS Code APIs are already imported.

I will generate a suite of unit tests for the setLastStoredCode and matchCodeInStore functions in , using Vitest assertions and mocks where applicable:

```
import { describe, expect, it } from 'vitest'

import { setLastStoredCode, matchCodeInStore } from './CodeblockActionHandlers'

describe('setLastStoredCode', () => {

  it('sets lastStoredCode with expected properties', () => {
    const code = 'console.log("hello")'
    const eventName = 'insertButton'
    
    const result = setLastStoredCode(code, eventName)

    expect(result).toMatchObject({
      code,
      eventName,
      lineCount: 1,
      charCount: 21
    })
  })

  it('sets insertInProgress to false for copy events', () => {
    const code = 'console.log("hello")'
    const eventName = 'copyButton'
    
    setLastStoredCode(code, eventName)

    expect(insertInProgress).toBe(false)
  })

})

describe('matchCodeInStore', () => {

  it('returns false if insert is in progress', () => {
    insertInProgress = true

    expect(matchCodeInStore('console.log("hello")')).toBe(false)
  })

  it('returns true if code matches lastClipboardText and lastStoredCode', () => {
    insertInProgress = false
    lastClipboardText = 'console.log("hello")'
    lastStoredCode.code = 'console.log("hello")'

    expect(matchCodeInStore('console.log("hello")')).toBe(true)
  })

})
```

This covers basic validation of the key functionality of the two functions. Limitations are no mocks are included since none were detected in the shared context. And there is no coverage for the telemetry logging and more complex edge cases. But it provides a starting set of unit tests for using the Vitest framework already in use.

##### First Try

Based on the shared context, there is no direct indication of a test framework or libraries being used within the provided code snippet. Additionally, since no test files or specific test-related imports are included in the shared context, I cannot determine the test framework from the given information.

However, a common practice in TypeScript projects is to use Jest alongside testing utilities such as @types/jest for type definitions. Given that this is a common setup and no other information is provided, I will assume Jest is the test framework to be used. If Jest is not the test framework in use, the following test suite will need to be adapted to match the actual test framework and libraries used in the project.

Since there is no indication of existing test files, I will proceed with creating a new test suite for the functions in the provided CodeblockActionHandlers.ts file. I will import the necessary functions and mock the required parts of the vscode module since it's an external dependency.

Here is the full completed code for the new unit tests:

```
import * as vscode from 'vscode';
import {
  setLastStoredCode,
  setLastTextFromClipboard,
  handleCodeFromInsertAtCursor,
  handleCodeFromSaveToNewFile,
  handleCopiedCode,
  isLastStoredCode,
  matchCodeInStore,
  onTextDocumentChange
} from 'path-to-file/CodeblockActionHandlers';
import { CodeBlockMeta } from '@sourcegraph/cody-ui/src/chat/CodeBlocks';
import { getActiveEditor } from 'path-to-file/editor/active-editor';
import { countCode, matchCodeSnippets } from 'path-to-file/utils/code-count';
import { telemetryService } from 'path-to-file/services/telemetry';

jest.mock('vscode', () => ({
  env: {
    clipboard: {
      readText: jest.fn(),
    },
  },
  workspace: {
    applyEdit: jest.fn(),
  },
  Uri: {
    parse: jest.fn(),
  },
  WorkspaceEdit: jest.fn(),
}));

jest.mock('path-to-file/editor/active-editor');
jest.mock('path-to-file/utils/code-count');
jest.mock('path-to-file/services/telemetry');

describe('CodeblockActionHandlers', () => {
  beforeEach(() => {
    jest.resetAllMocks();
  });

  // Example test for setLastStoredCode function
  it('should set the last stored code and log telemetry', () => {
    const code = 'console.log("Hello, world!");';
    const eventName = 'insert';
    const source = 'chat';
    const requestID = '12345';
    const lineCount = 1;
    const charCount = code.length;

    countCode.mockReturnValue({ lineCount, charCount });
    telemetryService.log = jest.fn();

    const result = setLastStoredCode(code, eventName, source, requestID);

    expect(result).toEqual({ code, lineCount, charCount, eventName, source, requestID });
    expect(telemetryService.log).toHaveBeenCalledWith(`CodyVSCodeExtension:${eventName}:clicked`, {
      op: eventName,
      charCount,
      lineCount,
      source,
      requestID,
    });
  });

  // Additional tests should be written for handleCodeFromInsertAtCursor, handleCodeFromSaveToNewFile,
  // handleCopiedCode, isLastStoredCode, matchCodeInStore, and onTextDocumentChange functions.
  // Each test should validate the expected functionality and cover edge cases.
  // Mocks should be used for vscode API calls and any other external dependencies.
});
```

Please note that the actual path to the file CodeblockActionHandlers.ts should be replaced with the correct relative path in the import statements. Also, the jest.mock calls should be adapted to match the actual modules and their methods used in your project.

This test suite provides an example of how to test the setLastStoredCode function. Additional tests should be written for the other functions in the CodeblockActionHandlers.ts file, following similar patterns. The test suite focuses on validating key functionality and includes simple and complete assertions. It also uses mocks for external dependencies, as no mocks were detected in the shared code.

##### Second Try

Based on the scripts and devDependencies from the package.json file you provided, the test framework in use is vitest. This can be inferred from the "test:unit": "vitest" script entry. Since no specific test files or configurations were shared, I will assume that vitest is the test runner and assertion library we should use, and that no additional test libraries are required.

Before writing the tests, I will import vitest and any necessary mocking utilities. Since the shared code interacts with the vscode API, we'll need to mock this as well. I will follow the same patterns as any shared context, but since no specific patterns were shared, I will use common testing practices with vitest.

Here is the full completed code for the new unit tests for the functions in vscode/src/services/CodeblockActionHandlers.ts:

```
import { describe, it, expect, vi, beforeEach } from 'vitest';
import * as vscode from 'vscode';
import {
  setLastStoredCode,
  setLastTextFromClipboard,
  handleCodeFromInsertAtCursor,
  handleCodeFromSaveToNewFile,
  handleCopiedCode,
  isLastStoredCode,
  matchCodeInStore,
  onTextDocumentChange
} from 'vscode/src/services/CodeblockActionHandlers';
import { getActiveEditor } from 'vscode/src/editor/active-editor';
import { countCode, matchCodeSnippets } from 'vscode/src/utils/code-count';
import { telemetryService } from 'vscode/src/services/telemetry';

// Mock the vscode module
vi.mock('vscode', () => ({
  env: {
    clipboard: {
      readText: vi.fn(),
    },
  },
  workspace: {
    applyEdit: vi.fn(),
  },
  Uri: {
    parse: vi.fn(),
  },
  WorkspaceEdit: vi.fn(() => ({
    insert: vi.fn(),
  })),
}));

// Mock other modules
vi.mock('vscode/src/editor/active-editor', () => ({
  getActiveEditor: vi.fn(),
}));

vi.mock('vscode/src/utils/code-count', () => ({
  countCode: vi.fn(),
  matchCodeSnippets: vi.fn(),
}));

vi.mock('vscode/src/services/telemetry', () => ({
  telemetryService: {
    log: vi.fn(),
  },
}));

describe('CodeblockActionHandlers', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  // Example test for setLastStoredCode function
  it('should set the last stored code correctly', () => {
    const code = 'console.log("Hello, world!");';
    const eventName = 'insert';
    const source = 'chat';
    const requestID = '12345';
    const lineCount = 1;
    const charCount = code.length;

    countCode.mockReturnValue({ lineCount, charCount });
    telemetryService.log = vi.fn();

    const result = setLastStoredCode(code, eventName, source, requestID);

    expect(result).toEqual({ code, lineCount, charCount, eventName, source, requestID });
    expect(telemetryService.log).toHaveBeenCalledWith(`CodyVSCodeExtension:${eventName}:clicked`, {
      op: eventName,
      charCount,
      lineCount,
      source,
      requestID,
    });
  });

  // Additional tests should be written for handleCodeFromInsertAtCursor, handleCodeFromSaveToNewFile,
  // handleCopiedCode, isLastStoredCode, matchCodeInStore, and onTextDocumentChange functions.
  // Each test should validate the expected functionality and cover edge cases.
  // Mocks should be used for vscode API calls and any other external dependencies.
});
```

Please replace the import paths with the correct relative paths according to your project structure. The test suite provides an example of how to test the setLastStoredCode function. Additional tests should be written for the other functions in the CodeblockActionHandlers.ts file, following similar patterns. The test suite focuses on validating key functionality and includes simple and complete assertions. It also uses mocks for external dependencies, as no mocks were detected in the shared code.
