### ISSUE TITLE
VSCE: New Chat - @ file context via chat input

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#1523]
<img width="1337" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/0f86ee66-348b-4fc5-b46c-a9237b8b3519">

<img width="503" alt="image" src="https://github.com/sourcegraph/cody/assets/68532117/dccf6c6d-80d7-47de-913b-ab1e218fd96c">

```[tasklist]
### Tasks
- [ ] VSCE New Chat: @ file - Display file and symbol match results in input area
- [ ] VSCE New Chat: @ file - Display added context in Chat view with clickable links
- [ ] VSCE New Chat: @ file - Create context message
- [ ] Add new context type for input context
```

#### part 1

![image](https://github.com/sourcegraph/cody/assets/68532117/4f8681e7-500f-44b4-8868-f9c6ba101fe3)

WIP: Display file and symbol match results in input area

https://github.com/sourcegraph/cody/pull/1549

![image](https://github.com/sourcegraph/cody/assets/68532117/c3d94f15-8a1e-486a-842f-eb203cb7dbe2)

#### part 2

![image](https://github.com/sourcegraph/cody/assets/68532117/b9d7f262-bccb-494c-9377-50e3388494e2)

Not started
