### ISSUE TITLE
Team settings - Ability to change Cody Pro billing interval and seat count

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1595]
As a billing owner on Cody Pro, I can change the details of my plan between renewal dates (increase/decrease seats, change from MTM to annual billing)

Requirements:

- A billing owner can change from monthly to annual billing (when annual billing is available)
  - Annual billing plan is $7.5/user/month, billed 1x per year ($90/user/year)
- A billing owner can change the number of seats.
  - An increase in seats will result in a prorated charge when the user confirms their increased seats
  - A decrease in seats will not result in a refund
- A billing owner can change change the credit card on the plan

Details here: https://docs.google.com/spreadsheets/d/1QXnrHkgGLXdbfHEhI_VjtDTy-mCtnK1qri3IMQu7rNk/edit#gid=1115406744
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/cody/issues/3361
- [ ] https://github.com/sourcegraph/self-serve-cody/issues/622
- [ ] https://github.com/sourcegraph/self-serve-cody/issues/514
```

Figma here: https://www.figma.com/file/sa3zkqScrSImHKvwfMKDN3/Cody-PLG-Map?type=whiteboard&node-id=671-2660&t=c3IOemcPredbBO91-0

**Comment by chenkc805** [comment]
Do we think we can have annual and MTM billing by February GA, or just MTM @vdavid ?

**Comment by vdavid** [comment]
Oh, sorry, I missed this ping because my Gmail filters were misconfigured. Fixed it now, won't miss pings in the future.

As per the latest [discussion](https://sourcegraph.slack.com/archives/C05SZB829D0/p1699564654292419?thread_ts=1699527167.587749&cid=C05SZB829D0), we'll handle annual plans as a nice-to-have for Feb, and add it 1–2 months later after the latest.

**Comment by chenkc805** [comment]
Bumping so this is not marked as stale. No action needed at the moment

**Comment by vdavid** [comment]
The "Team settings" page needs design. The closest page we have designed to this one is [here](https://www.figma.com/file/sa3zkqScrSImHKvwfMKDN3/Cody-PLG-Map?type=whiteboard&node-id=671-2660&t=c3IOemcPredbBO91-0).

**Comment by vdavid** [comment]
This is done, except for three things that are already tracked:
- Annual billing cycle: tracked by https://github.com/sourcegraph/self-serve-cody/issues/537
- Decrease seat counts: tracked by https://github.com/sourcegraph/sourcegraph/issues/63234
- https://github.com/sourcegraph/self-serve-cody/issues/881 (I've created this and assigned it to @chenkc805)

**Comment by robmorgan** [comment]
Are there any updates on Cody Pro Annual Billing? Note: I can't access: https://github.com/sourcegraph/self-serve-cody/issues/537

**Comment by vdavid** [comment]
@robmorgan, I'm not with Sourcegraph anymore, but I'm sure someone from the current team will get back to you shortly! Pinging @chenkc805 to coordinate or answer.

**Comment by robmorgan** [comment]
@vdavid Hey David, thanks for the reply! Not a problem.
