### ISSUE TITLE
Tracking issue: 11/1 - 11/15

### ISSUE THREAD

**Issue by beyang** [sourcegraph/cody#1610]
```[tasklist]
### Tasks > misc
- [ ] https://github.com/sourcegraph/cody/issues/1049
- [ ] [dominic or danny] Pricing tiers UX, Pro trial, Community Edition limits, current edition visible + upgrade CTA, rate limit enforcement
- [ ] [TODO] JetBrains-specific work
```

```[tasklist]
### Tasks > chat
- [ ] https://github.com/sourcegraph/cody/issues/1377
- [ ] https://github.com/sourcegraph/cody/issues/1410
- [ ] https://github.com/sourcegraph/cody/issues/1010
- [ ] [beatrix] Make use of GPT-4 and GPT-3.5 in chat
- [ ] [beyang] Keyword context for chat
- [ ] [dominic] Appless embeddings
```

```[tasklist]
### Tasks > commands
- [ ] https://github.com/sourcegraph/cody/issues/1475
- [ ] https://github.com/sourcegraph/cody/issues/1359
- [ ] [tom] Fixups: inline code edits, latency and reliability; perhaps personal prompt prefix
- [ ] https://github.com/sourcegraph/cody/issues/1464
- [ ] https://github.com/sourcegraph/cody/issues/1545
- [ ] https://github.com/sourcegraph/cody/issues/1378
- [x] [tom] add option to skip formatting config and improve UX
- [ ] [tom] prototype for applying fixup edits as they stream in
- [ ] [beyang] NLS search
- [ ] [kevin + beyang] Loveability metrics for commands/chat
```

```[tasklist]
### Tasks > completions
- [ ] [valery] Full function completions / completion use cases
- [ ] https://github.com/sourcegraph/cody/issues/1455
- [ ] [auguste + tj] BFG
- [ ] https://github.com/sourcegraph/cody/issues/1366
- [ ] https://github.com/sourcegraph/cody/issues/1050
- [ ] https://github.com/sourcegraph/cody/issues/1369
```

```[tasklist]
### Revisit Nov 15
- [ ] https://github.com/sourcegraph/cody/pull/1152
- [ ] [Automated release process with integration test for all clients](https://sourcegraph.slack.com/archives/C04MZPE4JKD/p1696866464146509?thread_ts=1696444672.205249&cid=C04MZPE4JKD)
- [ ] [unassigned] Block Cody abuse by checking against prompt templates ([context](https://sourcegraph.slack.com/archives/C0C324C91/p1696322332990229))
- [ ] [unassigned] [Pin LLM versions](https://sourcegraph.slack.com/archives/C05AGQYD528/p1695849038538219?thread_ts=1695848852.257419&cid=C05AGQYD528)
- [ ] [unassigned] Try [long-context Mistral](https://twitter.com/theemozilla/status/1720107186850877662)
```

```[tasklist]
### Revisit January 2024
- [ ] https://github.com/sourcegraph/cody/issues/1370
- [ ] Multiregion deployment
```

**Comment by beyang** [comment]
Retiring in favor of https://github.com/orgs/sourcegraph/projects/387
