### ISSUE TITLE
[Umbrella]: Cody context selector UI enhancements 

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#166]
Cody context selector UI is confusing in an App context and impedes onboarding. In the Cody App onboarding the Chat UI is the final all-important step where they try Cody for real, and the context selector UI presents some big hurdles for people to get started.

```[tasklist]
### Working issues (ordered by priority)
- [x] p0: sourcegraph/cody#160
- [x] p1: sourcegraph/cody#161
- [ ] p1: <del>Remove context selector search</del> Make sure search input labels aren't confusing the add/removing repos to the app itself
- [x] p1: sourcegraph/cody#162
- [x] p2: https://github.com/sourcegraph/cody/issues/163
- [ ] p2: sourcegraph/cody#164
- [x] p2: sourcegraph/cody#165
- [x] p1: sourcegraph/sourcegraph#54107
- [x] p0: https://github.com/sourcegraph/sourcegraph/issues/54086
- [x] p0: sourcegraph/sourcegraph#54007
- [x] p0: sourcegraph/sourcegraph#54012
```

### Issues

1. It doesn't include any repositories by default

https://github.com/sourcegraph/sourcegraph/assets/153/8ffd5dbe-8db7-4a2b-9afb-69a268eb8eba

2. The search filtering isn't working as expected

https://github.com/sourcegraph/sourcegraph/assets/153/7db12346-75e9-4ca5-8ba8-7f6ab94cde5a

3. The context selector repo UI copy and design misleads people into thinking it's where you manage your repositories

<img width="1136" alt="Screenshot 2023-06-21 at 6 41 58 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/3d11d751-69db-49f1-9aae-f1c13c4ca1b3">

4. When you finally enable a repo in the chat, the embedding status tells people to enable embeddings (but it will be automatically kicked off… people just need to wait for it to finish):

<img width="1136" alt="Screenshot 2023-06-21 at 6 47 13 pm" src="https://github.com/sourcegraph/sourcegraph/assets/153/82b1a510-22b1-46b5-a611-c824aba1a64a">

## References

See Slack conversation: https://sourcegraph.slack.com/archives/C01U8SJUKJM/p1687332618711079?thread_ts=1687226876.693649&cid=C01U8SJUKJM
