### ISSUE TITLE
[Tracking issue]: Improvements and Bugs fixes for December GA

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#1930]
```[tasklist]
### Tasks
- [ ] ------------ TODO -------------
- [ ] https://github.com/sourcegraph/cody/issues/2229
- [ ] -------------------- IN REVIEW ------------------
- [ ] ---------------- FOLLOW UP OTHERS -------------------
- [ ] ----------------------- DONE -----------------------
- [ ] https://github.com/sourcegraph/cody/issues/2309
- [ ] https://github.com/sourcegraph/cody/issues/1873
- [ ] https://github.com/sourcegraph/cody/issues/1993
- [ ] https://github.com/sourcegraph/cody/issues/2276
- [ ] https://github.com/sourcegraph/cody/issues/2230
- [ ] https://github.com/sourcegraph/cody/issues/2310
- [ ] https://github.com/sourcegraph/cody/issues/1931
- [ ] https://github.com/sourcegraph/cody/issues/1994
- [ ] https://github.com/sourcegraph/cody/issues/2163
- [ ] https://github.com/sourcegraph/cody/issues/2231
- [ ] https://github.com/sourcegraph/cody/issues/2249
- [ ] https://github.com/sourcegraph/cody/issues/2081
- [ ] https://github.com/sourcegraph/cody/issues/1992
- [ ] https://github.com/sourcegraph/cody/issues/2019
- [ ] https://github.com/sourcegraph/cody/issues/2012
- [ ] https://github.com/sourcegraph/cody/issues/1934
- [ ] https://github.com/sourcegraph/cody/issues/1964
- [ ] https://github.com/sourcegraph/cody/issues/1936
- [ ] https://github.com/sourcegraph/cody/issues/1933
- [ ] https://github.com/sourcegraph/cody/issues/1932
- [ ] https://github.com/sourcegraph/cody/issues/1937
- [ ] https://github.com/sourcegraph/cody/issues/1995
- [ ] https://github.com/sourcegraph/cody/issues/2160
- [ ] https://github.com/sourcegraph/cody/issues/2054
- [ ] https://github.com/sourcegraph/cody/issues/2056
- [ ] https://github.com/sourcegraph/cody/issues/1959
- [ ] https://github.com/sourcegraph/cody/issues/1960
- [ ] https://github.com/sourcegraph/cody/issues/1935
```

**Comment by chenkc805** [comment]
CC: @danielmarquespt @thenamankumar @vdavid @kalanchan  for visibility

**Comment by vdavid** [comment]
Everything is done here except one item which is on the board, so closing this; we can return to using the board.

@chenkc805, feel free to reopen this if it suits your workflow better to keep on using this in the remaining few hours.
