### ISSUE TITLE
Embeddings: migrate between different embedding models

### ISSUE THREAD

**Issue by novoselrok** [sourcegraph/cody#216]
We need to start a conversation about providing a smooth transition from OpenAI embedding models to our own models. And, more importantly, how we can design a generic transition between any two embedding models in the future. This is what is going to enable us to provide our customers with the latest and greatest model we have to offer.

What’s the crux of the issue?

Let’s say we have two embedding models: an older model A and a newer model B, and all of the customers’ code is indexed with model A. Once customers switch their config to a new embedding model B they won’t be able to use their old indexes because model A and model B are incompatible. Customers will have to drop the old model A repo indexes and re-schedule embeddings with the new model B. This will result in Cody downtime while repos are being indexed.

A solution would be to keep customers using old model A indexes while model B indexes are being created. But that would require that we still have access to the model A config (access token, dimensions, etc.) for query purposes. This will require a lot of careful orchestration, and we have to find a way to surface the details to the site-admin, where necessary.

```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55983
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55984
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55982
- [ ] https://github.com/sourcegraph/sourcegraph/issues/55975
```
