### ISSUE TITLE
[Tracking issue] Cody Dec GA Tech Debt Cleanup

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#2356]
```[tasklist]
### Tasks
- [ ] Centralize code for all pricing pages (/cody/subscription, /pricing) so that plan information can be changed from 1 central source
- [ ] Drop the Pro abuse limits back down
- [ ] [Idea] How can we have sandbox links for sharing QA without having to deploy to prod or locally build an env?
- [ ] https://github.com/sourcegraph/accounts.sourcegraph.com/issues/128
```

**Comment by vdavid** [comment]
Thanks for collecting these, @chenkc805!
Notes:
- The item “Remove Cody Pro feature flag” is a duplicate of https://github.com/sourcegraph/accounts.sourcegraph.com/issues/128 which already contains some context.
- The "Drop the Pro abuse limits back down" would probably be better as a calendar item as it's time-bound?

Meta:
Do you think we could go back to using the board (rather than a tracking issue) post-launch?
It'd be easier to add and track all the properties of these items, and have discussions about them. If it helps, we can convert them to issues and leave them in a tracking issue, but it'd be a lto more convenient for me if we could go back to the board for the source of truth.

**Comment by chenkc805** [comment]
Yeah let's move back to using the PLG Project. I'll create a separate custom field specifying this work
