### ISSUE TITLE
VS Code 1.0.0 Checklist

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#2366]
- [x] Ensure we have a fix for free/pro rate limiting upsells https://sourcegraph.slack.com/archives/C05AGQYD528/p1702531873832029
- [ ] Update readme: https://sourcegraph.slack.com/archives/C05AGQYD528/p1702482030030899
- [ ] Flip feature flags
- [ ] Merge #2357
- [ ] Test Free/Pro Rate Limits
  - Use tokens from [here](https://docs.google.com/document/d/1qYDsO6GOxGHEB2ZRSO9BWgjTra2adw0y3BDTNkjZqZw/edit#heading=h.honoxdjvt5gj)
  - [ ] Free users hit rate limits and get upgrade CTAs on chat/commands and autocomplete
  - [ ] Pro users hit rate limits and get "learn more" CTAs on chat/commands and autocomplete
- [ ] Roll out VS Code
   - [ ] Insider
   - [ ] Stable

**Comment by kalanchan** [comment]
I added free/pro rate limit testing, theres a known bug right now but we don't know if it's the client or the gateway 

https://sourcegraph.slack.com/archives/C05AGQYD528/p1702531873832029

**Comment by philipp-spiess** [comment]
We shipz
