### ISSUE TITLE
Post GA community bug reports

### ISSUE THREAD

**Issue by beyang** [sourcegraph/cody#2464]
## Chat
- ~@-mentioning can't include more than one file: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1186583699446321232 + https://discord.com/channels/969688426372825169/1134090651424800848/threads/1187776828992131152~ @taylorsperry tested on v 1.1.3 and seems to be working as expected; responded to both threads. 
- [x] Context window limit warning: https://discordapp.com/channels/969688426372825169/1188055420812660807/1188055420812660807
- https://github.com/sourcegraph/cody/issues/2513 GPT-4 error "failed to decode event payload": https://discord.com/channels/969688426372825169/1188826658824790016 (might be due to improper HTTP batching)

- [ ] <strike>Proposed solution: update UI to prefer one-off interactions over follow-up messages</strike>

Proposed solutions:
- [ ] Show "File is too large" when @'including large files ([design](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=331-103646&mode=design&t=VSb9ji9XwJ1EFY8j-4))
- [ ] Fix stuck "Stop Generating" button when @'including files that are too large
- [ ] Don't show "Context Limit Reached - Start New Chat" when @'including large files that are too large, instead show them as "Ignored (too large)" in the list of context files (and expand the list by default)

## Inline edit
- Improper escaping: https://discord.com/channels/969688426372825169/1186585941494738944/1186585941494738944
created a [bug report](https://github.com/sourcegraph/cody/issues/2790)

~- Improper extraction: https://sourcegraph.slack.com/archives/C05AGQYD528/p1703187624737879~
@taylorsperry when I tried to repro on v 1.1.3, ~30 lines of code worked as expected; for 100 lines of code I saw a (nicer) error notification ("The amount of text selected exceeds Cody's current capacity") and the animation didn't stall out the way described. 
 
## Context quality
~- Irrelevant files: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1187475429775376545~
- Embeddings regeneration: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1187513067249074339
@taylorsperry I created an [issue](https://github.com/sourcegraph/cody/issues/2843) for this. 
- Error messages and poor formatting of `Explain code` message on Windows: https://discord.com/channels/969688426372825169/1187541611102613644/1187569764223164458

- [ ] Current proposed solution: switch to symf as the default context provider and add necessary UI indications when context is unavailable with clear explanation of the state and potential paths forward for the end user.

## Indexing 
Moved these to a new issue https://github.com/sourcegraph/cody/issues/2861 and tagged @dominiccooney 
~- Slow embeddings: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1184975203583934564~
~- Embedding indexing fails: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1185058388091076748~
~- Embeddings indexing fails: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1186013840899588096~
~- Reset embeddings index: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1182342978606473266~
~- Keep embeddings up to date: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1186219559225659423 + https://discord.com/channels/969688426372825169/1182342978606473266~
~- BFG download fails when Linux proxy is on: https://discord.com/channels/969688426372825169/1180397900379979877/1187822723725017168~

## Commands
- https://github.com/sourcegraph/cody/issues/2536 Enhanced context interferes with `smell` command: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1183873954075652247

## Search
- Download right version of `symf` on Android, investigate `symf` error: https://discord.com/channels/969688426372825169/1185893779526398022/1185908732064964719
https://discord.com/channels/969688426372825169/1185893779526398022/1188813434029096960
Bug report [here](https://github.com/sourcegraph/cody/issues/2846)
- Inscrutable search error: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1184974100255494144

## JetBrains
~- Build from source documentation confusing: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1186929553453633536~
- Only chat works: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1185222178069811330
~- Error when clicking on Cody icon: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1185777300759920700~

## Neovim
- ~Unable to find Cody commands: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1185297457190547577~
- Autocomplete not working: https://discord.com/channels/969688426372825169/1134090651424800848/threads/1187178528672862270 + https://discord.com/channels/969688426372825169/1134090651424800848/threads/1187725345730875392
- Logged out and unable to sign back in (not prompted for access token) https://discord.com/channels/969688426372825169/1134090651424800848/threads/1187773029233721384

## TODO after resolving this issue
- [ ] FUP with above threads in Discord
