### ISSUE TITLE
tracking: context limit issues with @-mentioned files

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#3455]
This is an issue spinned off from https://github.com/sourcegraph/cody/issues/2965 where the original goal was to display warnings for the @-mentioning massive files

Context: https://sourcegraph.slack.com/archives/C05AGQYD528/p1710331429302729

## Current state

Here is the current state of @-mentioning massive files summarized by @chillatom:

1. The file size "check" that we use to display the warning is not the real token limit applied by the system.  It is an approximation.  This leads to the odd behavior where we trigger a warning, but you can still include the file or you can successfully copy and paste the file contents into the chat message. 
2. The warning check is computed per file, which means that if file A & B are both individually under the estimated limit, we trigger no warning, even if A+B is above the limit.
3. If the file is actually too large to be included, but the user submits anyway (e.g. vscode/src/completions/logger.ts which is 860 LOC and ~6,700 tokens. It appears that we silently exclude the file from context and Cody hallucinates. :red_circle:
4. If the file triggers the warning, but isn't too large to be included e.g. vscode/src/local-context/symf.ts which is 641 LOC and 4,867 tokens, I see the content actually used as context and referenced correctly.

At a minimum it feels like we should do a few things

1. Tie our warning to the actual operation of the product.  If we say it's too large, the file should not be able to be input
2. We should not silently exclude a file that has been explicitly @ mentioned
3. Consider the case of multiple @ mentioned files
4. Prioritize @ mention files over other fetched context (not sure if we do this today) as to avoid silently removing the file explicitly referenced

Over a longer term, I think we should explore
- Expanding the context windows, especially for some of the flagship models (I'll be writing a proposal here)
- Consider summarization or [proposition extraction](https://arxiv.org/pdf/2312.06648.pdf) from the file

## Design Tasks

```[tasklist]
### Design Tasks:
- [x]  We should not silently exclude a file that has been explicitly @ mentioned - [figma](https://www.figma.com/file/jEsnzgsf0hNuJbqB9pKaGm/VS-Code---Cody---Commands-up-front-and-ChatGPT%2B%2B?type=design&node-id=1590-34814&mode=design&t=ZSpfaRg2b9wfCOfP-4)
```

## Engineering Tasks

```[tasklist]
### Engineering Tasks:
- [x] Tie our warning to the actual operation of the product. If we say it's too large, the file should not be able to be input
- [ ] https://github.com/sourcegraph/cody/issues/3522
- [x] Prioritize @ mention files over other fetched context (not sure if we do this today) as to avoid silently removing the file explicitly referenced
- [ ] https://github.com/sourcegraph/cody/issues/3364
- [ ] https://github.com/sourcegraph/cody/pull/3526
- [ ] https://github.com/sourcegraph/cody/pull/3548
- [ ] https://github.com/sourcegraph/cody/pull/3528
- [ ] https://github.com/sourcegraph/cody/pull/3523
- [ ] https://github.com/sourcegraph/cody/issues/3589
```

Other design ideas from @toolmantim : https://github.com/sourcegraph/cody/pull/3439#issuecomment-2005698701

**Comment by taylorsperry** [comment]
Just a note that once we've aligned on a path forward and those changes have shipped, we should ping @MaedahBatool to make sure the docs are up to date. (We know users have been confused about this.)

**Comment by kalanchan** [comment]
landed in v1.12
