### ISSUE TITLE
[Cody Ignore] Fetch, interpret enterprise Cody Ignore rules

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#3641]
Cody Ignore for Enterprise needs to interpret a different policy than the file-based .cody/ignore:

- The site config supports lists of repositories to be included/excluded from Cody's context following RE2 syntax
- If either include or exclude rules are defined, Cody applies these rules to determine which repositories can be used as context in requests to third-party LLMs
- If neither exclude nor include rules are specified, Cody may use content from any repository on the instance in its requests to third-party LLMs
- If both exclude and include rules are specified, the include rules restrict Cody to use content only from the repositories that match specified patterns. Repositories not matching any include patterns will be excluded.

Open question about what the defaults are, [see Slack thread.](https://sourcegraph.slack.com/archives/C06Q9R098N4/p1711667096619869)

### Related Docs
- [PRD](https://docs.google.com/document/d/10tD8n-5py4XWQD9c7doJB7zIuxa7lwiOkpo2d5NLlnA/edit#heading=h.10vr0jxhrd1r)
- [RFC910](https://docs.google.com/document/d/1PMeJHvY0ia2nMewFvs4vrFcmDbRDw9kSyljil-K8Pt8/edit#heading=h.trqab8y0kufp)

```[tasklist]
### Tasks
- [x] Add node RE2 package; the RFC specifies RE2
- [x] Fetch the enterprise rules with GraphQL
- [x] Provide a stub implementation for Sourcegraph endpoints which don't support this feature, with a liberal allow policy
- [x] Write a function which takes (repo, relative path) -> do/don't ignore
- [x] Migrate to re2-wasm
- [x] Write a function that takes file URI -> repo name based on the environment tools available.
- [x] Write a function that takes file URI -> do/don't ignore. Integrate it with both of the functions above.
- [x] Add Git submodules support
- [x] Update the context filters GraphQL based on the latest backend changes
- [x] Instantiate the context filters provider on the extension activation
- [x] Investigate the repo name resolution using the Sourcegraph GraphQL API
- [x] Add TODO about non-file URIs
- [x] Use all available remote URLs
- [x] ContextFilterProvider API should support notifications for publishing changes when the rules are changed on the backend, with polling
- [x] Expose API thru Agent for JetBrains and others, API should support notifications for publishing changes when the rules are changed on the backend (extension polls the backend)
- [x] Add agent integration tests
- [x] Do basic benchmarking for the `isUriAllowed` function for different scenarios, such as nested git submodules, huge repos like Chromium, and agent-based file system.
- [x] If the directory walk, git push URL lookup, etc. is too slow we'll need to cache more. (Hopefully not...)
- [ ] https://github.com/sourcegraph/cody/issues/3642
```

**Comment by cbart** [comment]
Does it make sense to work on a draft agent API that does something silly (allow only repos with J in the name?) to get jetbrains UI work unlocked?

**Comment by dominiccooney** [comment]
@cbart This idea started with me and has looped back this far, cool. We will do that if it makes sense for executing the plan. Decision at this point is JetBrains engineering is busy so there's no benefit to this right now.

**Comment by valerybugakov** [comment]
@cbart, it makes sense 👍

**Comment by valerybugakov** [comment]
Closing this issue since all the subtasks are completed and [[Cody Ignore] Fix risks arising from file based .cody/ignore](https://github.com/sourcegraph/cody/issues/3642) has its own standalone ticket.
