### ISSUE TITLE
[Cody Ignore] Fix risks arising from file based .cody/ignore

### ISSUE THREAD

**Issue by dominiccooney** [sourcegraph/cody#3642]
There's a file-based .cody/ignore feature, there's an remote configured Cody Ignore feature planned for Enterprise, we need to make these coherent. This records clean-up while reviewing the VSCode, extension code:

☢️ risk 👷 integrating new requirements w/ existing codegm 💪 defensive, mitigation 🧹 clean up

```[tasklist]
### Tasks
- [ ] ☢️ getContextFileFromDirectory, callers searches current directory without consulting cody ignore; passed thru edit user context files
- [ ] ☢️ getWorkspaceFilesContext searches workspace without consulting Cody Ignore
- [ ] ☢️ vscode/src/edit/prompt/context.ts getContext passes thru "user" context without checking Cody Ignore
- [ ] ☢️ vscode/src/editor/vscode-editor.ts getTextEditorContextForFile does not check Cody Ignore
- [ ] 👷 Expand ignore concept to repos, eg vscode/src/chat/ContextProvider.ts updateCodebaseContext should filter ignored repos
- [ ] 💪 Security review
- [ ] 💪 Audit uses of VSCode document getText, etc.
- [ ] 💪 vscode/src/prompt/index.ts buildInteraction uses fixup file URI without checking ignore, strengthen this
- [x] 💪 Consider carrying file, editor content substrings in objects, not strings; use template literals for concatenation preserving taint.
- [ ] 🧹 ~vscode/src/editor/active-editor.ts caches lastActiveTextEditor for no purpose~ (the cache is effective, via `getEditor`)
- [x] 🧹 `check/isCodyIgnoredFile` is unused (at least in JetBrains) in Agent protocol, so remove it; API as designed is weird (takes a list of files, returns a single boolean) and wasteful (checks all of the files to return `true` even if the first file is `true`)
- [ ] 🧹 There are "chat based" and "new" edit, unit test commands. Minimize risk by deprecating, removing unused commands.
- [ ] What's the plan for context? Do we require user prompts to be promptstring?
- [ ] PromptString: Revisit the type for storing references. https://github.com/sourcegraph/cody/pull/3734#discussion_r1562182819
- [ ] PromptString: Handle serialization of chat transcriptions with a resolved reference.
- [ ] PromptString: Can we guarantee that filters are honored? https://github.com/sourcegraph/cody/pull/3856#issuecomment-2069272652
```

**Comment by abeatrix** [comment]
@dominiccooney For the ☢️ items, IIRC we removed isCodyIgnored checks from those on purpose because we have moved them to the prompt constructing step in [SimpleChatModel](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/chat/chat-view/SimpleChatModel.ts?L35-44) and [prompt-builder](https://sourcegraph.com/github.com/sourcegraph/cody/-/blob/vscode/src/prompt-builder/index.ts?L124-127) where context will be filtered before the request is sent to the LLM.

**Comment by dominiccooney** [comment]
@abeatrix thanks for the pointers, I have moderated the language in the issue a bit—defects to risks, etc.

We still need to clean this up, because it relies on really long range dependencies lining up and staying aligned. For example, if EditManager.executeEdit are passed configuration.document that doesn't belong to the active editor, then we check whether the *editor* is ignored, but I believe we can pass the document+selection down to buildGenericPrompt and put the selection in the instruction.
