### ISSUE TITLE
Tracking issue: 8/7 - 8/18

### ISSUE THREAD

**Issue by beyang** [sourcegraph/cody#582]
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/cody/issues/583
- [ ] https://github.com/sourcegraph/cody/issues/620
- [ ] https://github.com/sourcegraph/cody/issues/672
- [ ] https://github.com/sourcegraph/cody/issues/628
- [ ] https://github.com/sourcegraph/cody/issues/633
- [ ] https://github.com/sourcegraph/cody/issues/639
- [ ] https://github.com/sourcegraph/cody/issues/640
- [ ] https://github.com/sourcegraph/cody/issues/653
- [ ] https://github.com/sourcegraph/cody/issues/654
- [ ] https://github.com/sourcegraph/cody/issues/666
- [ ] https://github.com/sourcegraph/cody/issues/685
- [ ] https://github.com/sourcegraph/cody/pull/718
```

```[tasklist]
### Abandon
- [ ] https://github.com/sourcegraph/cody/issues/589
```

```[tasklist]
### Pushed
- [ ] https://github.com/sourcegraph/cody/issues/619
- [ ] https://github.com/sourcegraph/cody/issues/618
- [ ] https://github.com/sourcegraph/cody/issues/632
- [ ] https://github.com/sourcegraph/cody/issues/373
```

```[tasklist]
### Revisit next sprint
- [ ] https://github.com/sourcegraph/cody/issues/588
- [ ] https://github.com/sourcegraph/cody/issues/587
- [ ] https://github.com/sourcegraph/cody/issues/585
- [ ] https://github.com/sourcegraph/cody/issues/631
- [ ] https://github.com/sourcegraph/cody/issues/634
- [ ] https://github.com/sourcegraph/cody/issues/667
- [ ] https://github.com/sourcegraph/cody/issues/716
```

```[tasklist]
### Tasks
```

**Comment by kalanchan** [comment]
## Release v0.6.7

```[tasklist]
### Committed
- [ ] #620 
- [ ] #672 
- [ ] #628 
- [ ] #639 
```

```[tasklist]
### Pending
- [ ] https://github.com/sourcegraph/cody/issues/583
- [ ] https://github.com/sourcegraph/cody/issues/589
- [ ] https://github.com/sourcegraph/cody/issues/618
- [ ] https://github.com/sourcegraph/cody/issues/373
- [ ] https://github.com/sourcegraph/cody/issues/632
- [ ] https://github.com/sourcegraph/cody/issues/633
- [ ] https://github.com/sourcegraph/cody/issues/640
- [ ] https://github.com/sourcegraph/cody/issues/653
- [ ] https://github.com/sourcegraph/cody/issues/654
- [ ] https://github.com/sourcegraph/cody/issues/666
- [ ] https://github.com/sourcegraph/cody/issues/685
```

**Comment by kalanchan** [comment]
```[tasklist]
### My tasks
- [ ] https://github.com/octo-org/octo-repo/issues/45
- [ ] Draft task
```
