### ISSUE TITLE
Update old links to new repo/discussions

### ISSUE THREAD

**Issue by jdorfman** [sourcegraph/cody#6]
```[tasklist]
### Tasks
- [x] About
- [x] social
- [x] VS Code
- [x] Create loom for Maedah (https://www.loom.com/share/761fab8cacbe4e69a3076d8a01574ac0)
- [x] app (Yes [app will stay in sourcegraph/sourcegraph] it contains all the code of an enterprise deployment)
- [x] Docs (ping Maedah)
- [x] .com (https://sourcegraph.com/search?q=context:global++repo:sourcegraph/.*+cody+AND+https://github.com/sourcegraph/sourcegraph&patternType=standard&sm=1&groupBy=repo)
- [x] Contributing.md missing
- [x] JetBrains (https://sourcegraph.slack.com/archives/C0454UB6AL8/p1689175013092969)
- [ ] https://github.com/sourcegraph/cody/pull/110
```

```[tasklist]
### .com mentions, open pr, ping Maedah
- [x] https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/doc/cody/troubleshooting.md?L3
- [ ] https://github.com/sourcegraph/sourcegraph/pull/54860
```

```[tasklist]
### JetBrains
- [ ] https://github.com/sourcegraph/cody/issues/155
- [x] https://plugins.jetbrains.com/plugin/9682-cody-ai-by-sourcegraph
- [x] Ping David (on it)
- [x] Issue Tracker - https://github.com/sourcegraph/cody/issues
- [x] Forum Page - https://github.com/sourcegraph/cody/discussions
- [x] Documentation - https://sourcegraph.com/github.com/sourcegraph/sourcegraph/-/blob/client/jetbrains/README.md
```

**Comment by jdorfman** [comment]
@taylorsperry @slimsag are we going to keep the [app issues repo](https://github.com/sourcegraph/app/issues) separate or do we want to merge it to [cody](https://github.com/sourcegraph/cody)?

<img width="542" alt="Image 2023-07-10 at 12 05 19 PM png" src="https://github.com/sourcegraph/cody/assets/398230/f07554f2-ab0b-4d30-922e-1ddc0b6b781e">

**Comment by jdorfman** [comment]
David will update our JetBrains plugin page when his team is ready
