### ISSUE TITLE
Finalize Commands and Custom Commands

### ISSUE THREAD

**Issue by abeatrix** [sourcegraph/cody#620]
```[tasklist]
### Tasks
- [x] replace existing walkthrough for recipes with commands https://github.com/sourcegraph/cody/pull/648
- [x] Welcome message to notify users about the new Commands https://github.com/sourcegraph/cody/pull/648
- [x] Draft user docs: https://sourcegraph.com/notebooks/Tm90ZWJvb2s6MzA1NQ==
- [x] Log commands events with telemetry service
- [x] Add code smell command https://github.com/sourcegraph/cody/pull/602
- [x] Fix selection range issue caused by Inline Chat  https://github.com/sourcegraph/cody/pull/602
- [x] Add slash command via command menu https://github.com/sourcegraph/cody/pull/602
- [x] https://github.com/sourcegraph/cody/pull/683
- [x] https://github.com/sourcegraph/cody/pull/681
- [x] Update doc site to replace recipes with commands
```

Notes:
- [x] Marketing team is moving this to our doc site: https://sourcegraph.slack.com/archives/C04MSD3DP5L/p1691773322635569?thread_ts=1691747862.472519&cid=C04MSD3DP5L
  - Doc has been updated to use `commands` instead of `recipes`: https://docs.sourcegraph.com/cody/quickstart
- Usage has been up since the last release: https://sourcegraph.slack.com/archives/C05AGQYD528/p1692037224177669 

![image](https://github.com/sourcegraph/cody/assets/68532117/c3354071-0e36-4e52-8e6a-5ebe69aadb5c)

![image](https://github.com/sourcegraph/cody/assets/68532117/5dcc3f04-9622-4fa9-af9e-c182efa87a24)

Next:
- Tim is working on a new UI design with a better UX

**Comment by abeatrix** [comment]
🎉 Usage has been up since the last release: https://sourcegraph.slack.com/archives/C05AGQYD528/p1692037224177669
