### ISSUE TITLE
App-Less Onboarding Experience

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#632]
To reduce friction in getting started with Cody, we want to make downloading Cody App an optional step that happens much later in the onboarding process. This will mean:

- Sign In is via Sourcegraph.com or Enterprise Instance only
- Embeddings is done by talking to App on the side of the SG session (using App’s credentials from app.json file system?)

PRD: https://docs.google.com/document/d/1d3AsJeAB3AuUwAUTvvMzwKVQeVniX1Q06LPCBna5BbU/edit#heading=h.hu0rd8wz6rcd

Overall flow:
https://docs.google.com/drawings/d/1AboEUVSGurFaQqgZww-sNAwTj33GlbH7fpGnS6A1D-o/edit

Design wise, we'll need:
- A new sign in page
- A new "enable embeddings" bit of in-chat UI, and all the related interactions for adding, indexing, polling app for status, etc.
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/cody/issues/978
- [ ] https://github.com/sourcegraph/cody/issues/1051
- [ ] https://github.com/sourcegraph/cody/issues/1098
- [ ] https://github.com/sourcegraph/cody/issues/1212
- [ ] https://github.com/sourcegraph/cody/issues/1229
```

**Comment by chenkc805** [comment]
Sharing the spec here for visibility as well: https://docs.google.com/document/d/1d3AsJeAB3AuUwAUTvvMzwKVQeVniX1Q06LPCBna5BbU/edit#heading=h.hu0rd8wz6rcd

**Comment by toolmantim** [comment]
Draft designs for these are ready for [feedback in Figma](https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=4754-17329&mode=design&t=F1rgnbs2g5QZ4iY1-4)!

New sign in:

| As Spec'd | Backup Option |
| - | - |
| <img width="275" src="https://github.com/sourcegraph/cody/assets/153/8c0025d0-e58c-40bd-9cdf-d1303d66b907"> | <img width="275" src="https://github.com/sourcegraph/cody/assets/153/c88c7af1-3918-4a6c-b26d-f7b0afb42f35"> |


New welcome chat experience w/ optional app download:

| Welcome Chat | Clicking the Error Icon |
| - | - |
| <img width="275" src="https://github.com/sourcegraph/cody/assets/153/605874a0-a50c-451b-9a58-3f97c1a98023"> | <img width="275" src="https://github.com/sourcegraph/cody/assets/153/78b57fbc-82b4-4d22-b33e-bbaedb118395"> |

Notes:
- Email sign in option button links to https://sourcegraph.com/sign-up?showEmail=true
- Backup option if we want to piggy back off the existing https://sourcegraph.com/sign-up (which also has some good social proof content and other words)
- A new `vscode` value for `return-to` would need to be added
- Cody tagline copy was taken from the existing https://sourcegraph.com/sign-up

**Comment by toolmantim** [comment]
I've updated [the Figma](https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=4754-17329&mode=design&t=WvJcepme3DSbUmO6-4) with all of the states I can see we will need to handle.

We're probably also going to need to handle Cody Enterprise embeddings states as well in this update, so I'll work on those next to ensure we've got a view across everything going into the eng work.

**Comment by toolmantim** [comment]
@dominiccooney @chenkc805  here's a simplified design, focusing more on the simplified App-less sign-in, and less on creating a great embeddings experience:
https://www.figma.com/file/9112BsKsJc1BpO2j8XYwLL/%F0%9F%A4%96-Cody-VS-Code-%5BMain%5D?type=design&node-id=4840-19055&mode=design&t=dVlWUQdhHcMWSL7c-4

![image](https://github.com/sourcegraph/cody/assets/153/bed14983-4242-4dd1-ab69-fd8e7bf6dfad)

Design notes:
* Shows both the dot com and Enterprise experiences
* Assumes we have a way to tell via the API whether a repository exists or not, separately to whether it has embeddings
* Adds reloads buttons instead of live updates (which could just reload VS Code to begin with)
* No indication of indexing status, or inline buttons for adding a repo to App and kicking off embeddings generation
* Uses a neutral embeddings icon color instead of warning/error. If they start to use chat a lot without embeddings, and we know they might have a poor experience, there's some design options we can look at for notifying them to setup embeddings.

**Comment by dominiccooney** [comment]
Engineering update:
- I've done a bunch of spelunking of the sign up and login flows.
- Next step is to add a redirect to the onboarding survey page on dotcom.
- After that sign in with GitHub, GitLab, assume email should be readily achievable.
- Will work on the toasts to set up app for embeddings after that.

**Comment by chenkc805** [comment]
As per this Slack thread: https://sourcegraph.slack.com/archives/C05PC7AKFQV/p1694105019978109

@dominiccooney we're going to make 2 changes to the VScode signup flow in light of the security incident:
- We're going to get rid of email+pw signup in the VScode extension flow for now, until we figure out how to turn it back on that doesn't let in a bunch of abusers
- We want to replace email+pw with Google SSO instead.
CC @toolmantim @unknwon @bobheadxi

**Comment by vdavid** [comment]
This is all currently pretty specific to VS Code. Is that an intentional message, that is, we only want to adjust this flow for VS Code, or is this client only an example, and we want all clients to use this flow? I think our intention is the latter, and I'd, at the minimum, include adjusting the flow for JetBrains IDEs in this project.

Even if we decide to include JetBrains, it might not be worth it to tweak all our existing docs, issues, mocks, etc. with this in mind, but going forward, I suggest explicitly describing which clients we want to include and that VS Code is just one example.

**Comment by chenkc805** [comment]
I want us to test this first in VSCode before shipping to all clients. I'm fairly confident it will do well so we should build this in an extensible way for the other clients, but we'll test with VSCode first and then if it does well for VSCode, we'll ship to all other clients

**Comment by dominiccooney** [comment]
> we should build this in an extensible way for the other clients

@chenkc805 , @vdavid After we validate this is VScode, [here's a doc](https://docs.google.com/document/d/1yKQ3bNtqFVRTanQxPtDjCuM7iBCivBQ9gVEmR2ds714/edit#heading=h.5z0ujjco2th) outlining what other clients need to do. The way VScode is implementing this leans heavily on dotcom and the existing token provisioning method. Other clients should be able to adopt it without problem! 🎉 

@olafurpg had a similar question and has thought through the approach for JetBrains/IntelliJ. The doc is exactly what we discussed and adds more technical detail.

**Comment by dominiccooney** [comment]
[Doc with logging design.](https://docs.google.com/document/d/1XtsATx8lVPc-H2DvIM4FcIewOB0cCsf91Zj1BZMTxEg/edit) Thanks @chenkc805 for feedback. Will implement in a follow up to #1036

**Comment by chenkc805** [comment]
QA notes here: https://docs.google.com/spreadsheets/d/1bzrQT_QGYr0xstMSVj6U8DWbI5wbERFZKk41W7E-m2U/edit#gid=0

Overall seems good. It's hard to test new SG user flows with new GitHub accounts I just created, due to the security incident, but the one I was able to do (Google SSO) worked correctly (saw the "for work/personal" flow and then after that got pushed back to the IDE). So I think it's safe to assume Github and Gitlab probably work as well. 

You got the sign off from me! @toolmantim can you give this a look from the design POV?

**Comment by dominiccooney** [comment]
@chenkc805 , regarding

> But I saw my old chat history from another account showing in the chat. Is this because I didn't clear my Cody user settings thoroughly enough, so my chat logs are stored locally, and not associated with any SG account?

Yes, we use the tokens for accessing the LLMs but the state is stored locally and not associated with accounts. Good feedback for design that this is confusing.

**Comment by toolmantim** [comment]
@chenkc805 @dominiccooney looks good to me too! 🚀

**Comment by chenkc805** [comment]
@dominiccooney can you link all PRs related to this work here? I'm trying to organize them into this issue so this issue is the master issue and all your PRs are sub-tasks of this issue. That way we can keep track of this body of work in 1 place.

**Comment by chenkc805** [comment]
@dominiccooney when can we start QA'ing the post-sign in experience with the App? 

CC: @MaedahBatool as we'll probably need to update some docs around this

**Comment by chenkc805** [comment]
@dominiccooney can we close this?

**Comment by dominiccooney** [comment]
@toolmantim and I plan some follow-up design improvements this week, then we can close this.

**Comment by dominiccooney** [comment]
Onboarding is now app-less and we've done about as much clean up as we can without removing app entirely. I plan to track the work for completely app-less in #1443 so closing this issue now.
