### ISSUE TITLE
Tracking issue: 8/21 - 9/4

### ISSUE THREAD

**Issue by beyang** [sourcegraph/cody#750]
### Commands UI

This is not in a good state, we need to get it into a good state ASAP

* Command palette: all commands show up, so both /fix and /document should be present at the top level.
  * The "Submit a refactor" and "Submit question" options that appear if you start typing something else are inconsistent. These should correspond to a /command and indicate which.
  * We shouldn't group commands by whether they lead to a comment, the sidebar, or something else
  * Some basic intent mapping. If we can't do this fast enough beforehand, there should be some sort of confirmation afterwards.
* Sidebar REPL: all commands show up
* Inline REPL: I think we should eliminate this as a starting point for interactions (because we don't have an autosuggest capability in the text input here). We would still show this in case we need to show an inline response to the user, or maybe if the user wants to refine a /fix request.

### Commands

* Search across symbols
* Test - Make it a smooth UI for accepting the generated test
* Fix - needs very smooth UI for viewing and accepting/rejecting the change, or refining the instructions
  * Consolidate /fix, /document, "refactor" into single /edit command?
* Document - Smooth UI for easily accepting generated docs

```[tasklist]
### Tasks
- [ ] Search: indexed search improvements
- [ ] https://github.com/sourcegraph/cody/issues/772
- [ ] https://github.com/sourcegraph/cody/issues/760
- [ ] https://github.com/sourcegraph/cody/issues/634
- [ ] https://github.com/sourcegraph/cody/issues/630
- [ ] https://github.com/sourcegraph/cody/issues/754
- [ ] https://github.com/sourcegraph/cody/issues/809
- [ ] https://github.com/sourcegraph/cody/issues/631
- [ ] https://github.com/sourcegraph/cody/issues/619
- [ ] https://github.com/sourcegraph/cody/issues/618
- [ ] https://github.com/sourcegraph/cody/issues/588
- [ ] https://github.com/sourcegraph/cody/issues/587
- [ ] https://github.com/sourcegraph/cody/issues/585
- [ ] https://github.com/sourcegraph/cody/issues/800
- [ ] "Code Smell" → "Find Code Smells" (or "Detect Code Smells")
- [ ] https://github.com/sourcegraph/cody/issues/765
- [ ] https://github.com/sourcegraph/cody/issues/849
- [ ] https://github.com/sourcegraph/cody/issues/850
- [ ] https://github.com/sourcegraph/cody/issues/860
- [ ] https://github.com/sourcegraph/cody/issues/910
```

```[tasklist]
### Needs discussion
- [ ] https://github.com/sourcegraph/cody/issues/632
```

```[tasklist]
### Revisit next sprint
- [ ] https://github.com/sourcegraph/cody/issues/667
- [ ] .codyignore file
- [ ] Name suggestions feature
- [ ] Codelens CTAs
- [ ] https://github.com/sourcegraph/cody/issues/789
- [ ] Metrics for measuring impact of embeddings context on Loveability: https://docs.google.com/document/d/1UcjUdon1XO5GoLDIJJCGBq1zyhR6VfL2FE_apSPeLQo/edit#heading=h.wjyo6hfkbp25
- [ ] https://github.com/sourcegraph/cody/issues/867
```
