### ISSUE TITLE
Autocomplete: Prepare for StarCoder evaluation experiment

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#760]
```[tasklist]
### Tasks
- [x] Add support for fireworks across the backend stacks
- [x] Change the clients to use the SG A
- [x] rollout cody gateway changes
- [x] Feature flag to use fireworks as the default
```

**Comment by philipp-spiess** [comment]
We're good from the tech side
