### ISSUE TITLE
[Umbrella] Cody for VS Code onboarding experience

### ISSUE THREAD

**Issue by toolmantim** [sourcegraph/cody#84]
This is a parent issue for tracking how we're improving the onboarding flows on Cody VS Code, and in particular to how VS Code integrates with the Cody App.

## Tasks

```[tasklist]
### Todo
- [ ] https://github.com/sourcegraph/sourcegraph/issues/54225
- [ ] https://github.com/sourcegraph/sourcegraph/issues/54232
- [ ] https://github.com/sourcegraph/sourcegraph/issues/54226
- [ ] https://github.com/sourcegraph/cody/issues/86
- [ ] https://github.com/sourcegraph/sourcegraph/issues/54228
- [ ] https://github.com/sourcegraph/cody/issues/85
- [ ] https://github.com/sourcegraph/sourcegraph/issues/54231
- [ ] https://github.com/sourcegraph/cody/issues/95
```

```[tasklist]
### Done
- [ ] https://github.com/sourcegraph/sourcegraph/issues/54224
- [x] "Download Cody App" button in https://github.com/sourcegraph/sourcegraph/pull/52560
- [x] Native VS Code notifications in key setup places (login required, no embeddings, etc)
- [x] Walkthrogh
- [x] Improve login page design and copy
```

## Principles

- Optimise the minimum steps to aha moment (aka experiencing what makes Cody special) at all costs
- The experience should be delightfully simple
- All setup should be as automatic as possible
- After the first aha, help them to explore and go deeper

## Aha moment we're optimising for

A developer sends a message to Cody, on a private repo with embeddings enabled, and gets an insightful response

_(where an insightful response could be defined as not being a generic "Sorry" type message)_

## Impact on DAUs

* This work should have a high impact on DAUs by:
  1. Helping more new developers experience Cody’s value
  1. Setting up their IDE environment so they can continue to use it when writing code
* It is assumed that a very high percentage of new users will be new to SG (not have an existing account), and will want to try Cody out on their own private code. For private code, Cody App is required for embeddings, so the better we make VS Code <> App the higher chance of them making it to the aha moment.
