### ISSUE TITLE
Autocomplete × Graph Context tracking issue

### ISSUE THREAD

**Issue by philipp-spiess** [sourcegraph/cody#940]
- [x] When we refresh sections, make sure to update the ranges even if the  ID did not change
 - [x] Investigate why there are so many `\n` contents in the list (@philipp-spiess probably screwed up the markdown parser)
 - [ ] Can we keep sections up to date with every change 
    - [ ] Maybe treesitter would be better for extracting and maintaining sections
 - [ ] Rank results based on what is closest to the current cursor
 - [x] Find out why sometimes symbols are not included
    - repro: open `vscode/webviews/App.story.tsx`, click inside the `Simple` function, observe that `App` is not resolved.
 - [x] Find a way to _stop_ graph lookups to prevent freezes.
    - repro: open a large file with many functions, scroll around and click randomly so that many sections are hydrated
    - Proposal: Add support for a cancellation token to `getGraphContextFromRange` so that it can be cancelled if needed.
 - [ ] Better logic to prevent TypeScript interfaces to resolve to `interface <NameOfInterface>`
 - [ ] Investigate TS server perf regression
 - [ ] Sometimes the hover text has content from other extensions too (e.g. "Pretty TypeScript Errors") - Filter out the most common usages
 - [ ] Prompt testing a prompt to make sure the LLM actually understands these symbols
     - [ ] For Claude Instant
     - [ ] For StarCoder
 - [x] (optional) Integrate debug view into trace view

**Comment by philipp-spiess** [comment]
Closing this in favor of smaller issues if we decide to move forward here.
