### ISSUE TITLE
Implement Cody new user email flow v1

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#954]
Spec: https://docs.google.com/document/d/1d3AsJeAB3AuUwAUTvvMzwKVQeVniX1Q06LPCBna5BbU/edit#heading=h.tj5jdkcsnrl5
```[tasklist]
### Tasks
- [ ] https://github.com/sourcegraph/cody/issues/1008
- [x] send a new event 000020156310 VSCodyInstall to HubSpot every time the user installs the VS Code extension.
- [x] [add a new boolean property VSCodyEmailCampaignEnabled under ContactProperties to HubSpot. This will be controlled by a rollout feature flag.](https://github.com/sourcegraph/sourcegraph/pull/56669)
- [ ] Create telemetry requirements for Cody new user email flow
- [ ] https://github.com/sourcegraph/sourcegraph/pull/56669
```

**Comment by chenkc805** [comment]
Next steps:

- @thenamankumar to implement experiment enrollment for this test for dotcom users first, and pass that value over to @Shannonking456  for Hubspot email workflows
- @Shannonking456 to send test email by Monday EOD/early Tuesday to QA the email before shipping the test.

If all look good, let's target a ship date of 9/13. Thanks all

**Comment by chenkc805** [comment]
Lower priority than #632 and #958

**Comment by chenkc805** [comment]
PR here: https://github.com/sourcegraph/sourcegraph/pull/56669

**Comment by chenkc805** [comment]
Still working on getting telemetry for you @thenamankumar . Will hopefully have by EOD today

**Comment by chenkc805** [comment]
Apologies for the delay, here's the event: https://docs.google.com/document/d/1d3AsJeAB3AuUwAUTvvMzwKVQeVniX1Q06LPCBna5BbU/edit?disco=AAAA4am5Ork

I'm still working on understanding the email events we send from Hubspot, but that can be a fast follow. Let's start with the enrollment event as that's the most important thing.

**Comment by vdavid** [comment]
This is launched for JetBrains but not for VS Code. @thenamankumar, any ideas how we could make this work for VS Code?

**Comment by thenamankumar** [comment]
@vdavid as far as I remember, there was some issue receiving events from VS Code. If we are receiving events from VS Code in Hub Spot then there should not be any blockers.

**Comment by chenkc805** [comment]
Closing as defunct.
