### ISSUE TITLE
Spec out the new Cody App flow for new onboarding

### ISSUE THREAD

**Issue by chenkc805** [sourcegraph/cody#958]
```[tasklist]
### Subtasks
- [ ] https://github.com/sourcegraph/cody/pull/1090
- [ ] https://github.com/sourcegraph/sourcegraph/pull/56716
- [ ] https://github.com/sourcegraph/cody/pull/1089
```

**Comment by chenkc805** [comment]
@taylorsperry do you have the Figma for what the Cody app signup flow is? CC: @toolmantim

**Comment by toolmantim** [comment]
Thanks for creating the issue!

I've just gone and done the designs for this here:
https://www.figma.com/file/INGthyKM1cYki5H02JPDpW/VS-Code-Beta-2-%3C%3E-App-Onboarding?type=design&node-id=0-1&mode=design

cc @dominiccooney @thenamankumar

**Comment by taylorsperry** [comment]
This looks great!!

**Comment by chenkc805** [comment]
Removing all other assignees to just @thenamankumar for clarity

Answering Naman's question here: 

1. When the user opens the App some other time later, do they see Cody Chat or the settings page or nothing?
2. What if embeddings for 1 repo are in progress, and then they open another repo in VS Code and clicked on "Install App" for that repo. How do we show the progress status of two repos now?
3. We also have an embedding limit in the App. How do we communicate that they have already reached the limit?
4. What if they were on an old feature branch checked out locally when they clicked on "Install App," but now they went back to main. The embeddings are not updated, how do we communicate that they are stale?
5. Based on the designs if we want that on first install, the App should automatically start indexing the repo opened in VS Code, we will need to save that somewhere in the filesystem, and then App will read that file and always start indexing the repos on restart/install.
6. Is there a way for users to delete embeddings if they hit the limit, do we show them the current settings page? Where is that in the flow.

I'm going to organize my response based on the type of question:

- For usability questions (1, 2): For #1, I think they should see the settings page, since the Cody App as a client is going away in the near future. @taylorsperry can you confirm if you're aligned with this decision? For #2, I don't think they should see "Install App" if they've already installed the app and in the process of embedding a repo. In this case, users shouldn't be able to embed another repo if they already have 1 repo being embedded at the moment. They have to wait until their repo is finished embedding to embed another one. 
- For embeddings behavior in the App (3, 4, 6): Would it suffice to answer to keep the behavior as it is today? For example, for #4 I assume we're already running into this edge case where the branch the user is on doesn't match the branch that they generated embeddings on. Whatever we're doing there (maybe it's nothing), I could see us continuing to do what we're already doing

CC @toolmantim for viz.

**Comment by toolmantim** [comment]
I have moved the VS Code designs into https://www.figma.com/file/INGthyKM1cYki5H02JPDpW/VS-Code-Beta-2-%3C%3E-App-Onboarding?type=design&node-id=0-1&mode=design so we can look at everything in the one place, as well as put in the previous version of the VS Code design that @chenkc805 @dominiccooney and I went through before we simplified it. I assume you may not have seen some of this @thenamankumar and it may answer some of these questions.

> We also have an embedding limit in the App. How do we communicate that they have already reached the limit?

I don't think this is an actual hard limit at all… it's only enforced by the App during the welcome onboarding. Once you're through that, you can add as many as you like until dotcom starts returning quota exhausted errors.

**Comment by toolmantim** [comment]
> What if embeddings for 1 repo are in progress, and then they open another repo in VS Code and clicked on "Install App" for that repo. How do we show the progress status of two repos now?

They'd see this:
https://www.figma.com/file/INGthyKM1cYki5H02JPDpW/VS-Code-Beta-2-%3C%3E-App-Onboarding?type=design&node-id=53-468&mode=design&t=Ujl75QIN2V6zciwU-4

They would have to click Open App, manually add the repository, wait for it to be indexed in Cody App, go back to VS Code, and hit "Reload".

They would be using the Settings page of Cody App to see the indexing status.

(fyi there's a pretty bad usability bug in Cody App where it takes up to 1 minute for indexing to kick off after adding an additional repository — which confuses a lot of users because it just appears nothing is happening for a whole minute. If we could kick off this background job immediately instead of waiting for the policy to trigger it after a minute, that would be a huge win for user confidence)

**Comment by chenkc805** [comment]
@dominiccooney @thenamankumar I linked all the relevant PRs that I know about at the top of this issue to consolidate all the work into 1 place. Can you confirm that this is the right list of issues?

**Comment by chenkc805** [comment]
@thenamankumar @toolmantim did we ever align on whether we're going with "end-to-end flow (current)" or "end-to-end flow proposed (v2)" in the [Figma](https://www.figma.com/file/INGthyKM1cYki5H02JPDpW/VS-Code-Beta-2-%3C%3E-App-Onboarding?type=design&node-id=53-468&mode=design&t=pnSsBmLjBPdusFCZ-0)?

IMO I think "proposed (v2)" is better because a nice confirmation screen + legal text is helpful to show the user what we're doing. I think it'll feel surprising (in a bad way) to the user if we go with flow 1.

**Comment by toolmantim** [comment]
v2! 🙌🏼

**Comment by chenkc805** [comment]
@thenamankumar can we close this?

**Comment by vdavid** [comment]
I guess we can then
